app:
  auth:
    refresh-life-time: 120
    access-life-time: 30
  db:
    postgresql:
      host: "localhost"
      port: "5432"
      database: "auth"
      user: "auth"
      password: "auth"
      sslmode: disable
  log-level: "debug"
  default-role: "USER"